name: publish

on:
  release:
    types: [created]

jobs:
  run-cicd:
    uses: ./.github/workflows/cicd.yml
  publish:
    runs-on: ubuntu-latest
    needs: run-cicd
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
